In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv('../meal_with_preference.csv')
df.head()

,Main Meal,Side Meal,Complete Meal,Ingredients,Quantities,Meal_Ingredient_Ids,Energy(Kcal),Protein(g),Total fat(g),Carbohydrates(g),...,Phosphorus(mg),Magnesium(mg),Sodium(mg),Potassium(mg),Saturated Fatty Acids(mg),Monounsaturated Fatty Acids(mg),Polyunsaturated Fatty Acids(mg),Free sugar(g),Starch(g),Meal Time
0,Kottu Roti,Chicken Curry,Kottu Roti with Chicken Curry,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 40.0, 10.0, 5.0","SLB002, SLH006, SLJ002, SLK004, , SLI006",601.8,7.197,62.907,1.512,...,63.189,9.564,24.660,165.6,313.473,306.186,183.462,0.969,0.366,Dinner
1,Kottu Roti,Chicken Curry,Kottu Roti with Chicken Curry,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 40.0, 10.0, 5.0","SLB002, SLH006, SLJ002, SLK004, , SLI006",601.8,7.197,62.907,1.512,...,63.189,9.564,24.660,165.6,313.473,306.186,183.462,0.969,0.366,Dinner
2,Kottu Roti,Devilled Chicken,Kottu Roti with Devilled Chicken,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 50.0, 10.0, 5.0, 0.25, ...","SLB002, SLH006, SLJ002, SLK004, , SLI006, SLD060",609.9,7.800,62.985,2.523,...,73.332,32.049,29.895,274.2,341.676,307.830,213.399,1.113,0.696,Dinner
3,Kottu Roti,Devilled Fish,Kottu Roti with Devilled Fish,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 50.0, 10.0, 5.0, 0.25, ...","SLB002, SLH006, SLJ002, SLK004, , SLF006, SLI0...",609.9,7.800,62.985,2.523,...,73.332,32.049,29.895,274.2,341.676,307.830,213.399,1.113,0.696,Dinner
4,Kottu Roti,Seer Fish Curry,Kottu Roti with Seer Fish Curry,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 50.0, 25.0, 10.0","SLB002, SLH006, SLJ002, SLK004, , SLF025, SLI...",654.3,14.565,64.689,3.087,...,171.738,31.656,35.997,421.2,1021.173,640.428,731.262,1.269,0.942,Dinner

In [2]:
# in Meal time column some rows '/' seperated difference values so we need to split them and create new rows so that each split and add into list and add dataset again
df = df.assign(Meal_time=df['Meal Time'].str.split('/')).explode('Meal_time')

In [3]:
df.head()

,Main Meal,Side Meal,Complete Meal,Ingredients,Quantities,Meal_Ingredient_Ids,Energy(Kcal),Protein(g),Total fat(g),Carbohydrates(g),...,Magnesium(mg),Sodium(mg),Potassium(mg),Saturated Fatty Acids(mg),Monounsaturated Fatty Acids(mg),Polyunsaturated Fatty Acids(mg),Free sugar(g),Starch(g),Meal Time,Meal_time
0,Kottu Roti,Chicken Curry,Kottu Roti with Chicken Curry,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 40.0, 10.0, 5.0","SLB002, SLH006, SLJ002, SLK004, , SLI006",601.8,7.197,62.907,1.512,...,9.564,24.660,165.6,313.473,306.186,183.462,0.969,0.366,Dinner,Dinner
1,Kottu Roti,Chicken Curry,Kottu Roti with Chicken Curry,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 40.0, 10.0, 5.0","SLB002, SLH006, SLJ002, SLK004, , SLI006",601.8,7.197,62.907,1.512,...,9.564,24.660,165.6,313.473,306.186,183.462,0.969,0.366,Dinner,Dinner
2,Kottu Roti,Devilled Chicken,Kottu Roti with Devilled Chicken,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 50.0, 10.0, 5.0, 0.25, ...","SLB002, SLH006, SLJ002, SLK004, , SLI006, SLD060",609.9,7.800,62.985,2.523,...,32.049,29.895,274.2,341.676,307.830,213.399,1.113,0.696,Dinner,Dinner
3,Kottu Roti,Devilled Fish,Kottu Roti with Devilled Fish,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 50.0, 10.0, 5.0, 0.25, ...","SLB002, SLH006, SLJ002, SLK004, , SLF006, SLI0...",609.9,7.800,62.985,2.523,...,32.049,29.895,274.2,341.676,307.830,213.399,1.113,0.696,Dinner,Dinner
4,Kottu Roti,Seer Fish Curry,Kottu Roti with Seer Fish Curry,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 50.0, 25.0, 10.0","SLB002, SLH006, SLJ002, SLK004, , SLF025, SLI...",654.3,14.565,64.689,3.087,...,31.656,35.997,421.2,1021.173,640.428,731.262,1.269,0.942,Dinner,Dinner

In [4]:
df.head()

,Main Meal,Side Meal,Complete Meal,Ingredients,Quantities,Meal_Ingredient_Ids,Energy(Kcal),Protein(g),Total fat(g),Carbohydrates(g),...,Magnesium(mg),Sodium(mg),Potassium(mg),Saturated Fatty Acids(mg),Monounsaturated Fatty Acids(mg),Polyunsaturated Fatty Acids(mg),Free sugar(g),Starch(g),Meal Time,Meal_time
0,Kottu Roti,Chicken Curry,Kottu Roti with Chicken Curry,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 40.0, 10.0, 5.0","SLB002, SLH006, SLJ002, SLK004, , SLI006",601.8,7.197,62.907,1.512,...,9.564,24.660,165.6,313.473,306.186,183.462,0.969,0.366,Dinner,Dinner
1,Kottu Roti,Chicken Curry,Kottu Roti with Chicken Curry,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 40.0, 10.0, 5.0","SLB002, SLH006, SLJ002, SLK004, , SLI006",601.8,7.197,62.907,1.512,...,9.564,24.660,165.6,313.473,306.186,183.462,0.969,0.366,Dinner,Dinner
2,Kottu Roti,Devilled Chicken,Kottu Roti with Devilled Chicken,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 50.0, 10.0, 5.0, 0.25, ...","SLB002, SLH006, SLJ002, SLK004, , SLI006, SLD060",609.9,7.800,62.985,2.523,...,32.049,29.895,274.2,341.676,307.830,213.399,1.113,0.696,Dinner,Dinner
3,Kottu Roti,Devilled Fish,Kottu Roti with Devilled Fish,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 50.0, 10.0, 5.0, 0.25, ...","SLB002, SLH006, SLJ002, SLK004, , SLF006, SLI0...",609.9,7.800,62.985,2.523,...,32.049,29.895,274.2,341.676,307.830,213.399,1.113,0.696,Dinner,Dinner
4,Kottu Roti,Seer Fish Curry,Kottu Roti with Seer Fish Curry,"Roti, Vegetables, Chicken, Coconut Oil, Chil...","30.0, 40.0, 30.0, 2.5, 50.0, 25.0, 10.0","SLB002, SLH006, SLJ002, SLK004, , SLF025, SLI...",654.3,14.565,64.689,3.087,...,31.656,35.997,421.2,1021.173,640.428,731.262,1.269,0.942,Dinner,Dinner

In [5]:
df[df['Meal_time'] == 'Lunch']

,Main Meal,Side Meal,Complete Meal,Ingredients,Quantities,Meal_Ingredient_Ids,Energy(Kcal),Protein(g),Total fat(g),Carbohydrates(g),...,Magnesium(mg),Sodium(mg),Potassium(mg),Saturated Fatty Acids(mg),Monounsaturated Fatty Acids(mg),Polyunsaturated Fatty Acids(mg),Free sugar(g),Starch(g),Meal Time,Meal_time
13,Lamprais,Chicken Curry,Lamprais with Chicken Curry,"Rice, Meat, Spices, Chicken, Coconut milk","100.0, 30.0, 15.0, 40.0, 10.0","SLA008, SLH009, SLK004, SLH006, SLI006",1444.0,31.61,111.08,79.41,...,42.36,32.51,457.0,1495.08,1384.63,900.27,0.14,76.06,Lunch/Dinner,Lunch
14,Lamprais,Chicken Curry,Lamprais with Chicken Curry,"Rice, Meat, Spices, Chicken, Coconut milk","100.0, 30.0, 15.0, 40.0, 10.0","SLA008, SLH009, SLK004, SLH006, SLI006",1444.0,31.61,111.08,79.41,...,42.36,32.51,457.0,1495.08,1384.63,900.27,0.14,76.06,Lunch/Dinner,Lunch
30,Vegetable Fried Rice,Chicken Curry,Vegetable Fried Rice with Chicken Curry,"Rice, Vegetables, onion, Spices, curry leave...","100.0, 20.0, 20.0, 15.0, 3.0, 2.5, 40.0","SLA008, SLB002, SLD007, SLD060, SLI006, SLK004...",1559.0,41.66,112.83,90.83,...,313.01,121.40,1671.0,1924.84,1455.30,1791.06,4.47,81.32,Lunch/Dinner,Lunch
31,Vegetable Fried Rice,Parippu,Vegetable Fried Rice with Parippu,"Rice, Vegetables, onion, Spices, curry leave...","100.0, 20.0, 20.0, 15.0, 3.0, 2.5, 10.0, 5.0","SLA008, SLB002, SLD007, SLD060, SLI006, SLK004...",1991.0,46.10,113.95,188.36,...,638.83,137.78,4733.0,3330.84,1730.30,5855.06,6.38,164.36,Lunch/Dinner,Lunch
32,Vegetable Fried Rice,Wambatu Moju,Vegetable Fried Rice with Wambatu Moju,"Rice, Vegetables, onion, Spices, curry leave...","100.0, 20.0, 25.0, 5.5, 3.0, 2.5, 20.0, 10.0","SLA008, SLB002, SLD007, SLD060, SLI006, SLK004...",1383.0,18.52,103.59,90.83,...,292.83,90.98,1369.0,1146.84,471.30,1436.06,4.47,81.32,Lunch/Dinner,Lunch
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
632,Fish Biryani,"Chicken Curry, Chicken Curry, Ginger Chicken, ...","Fish Biryani with Chicken Curry, Chicken Curry...","Rice, Fish, , onion, Spices, curry leaves, ...","400.0, 200.0, 80.0, 20.0, 47.0, 10.8, 380.0, 7...","SLA008, SLF006, , SLD060, SLI006, SLK004, SLK0...",10736.0,274.48,885.60,401.88,...,1706.76,547.92,10272.0,21376.68,19275.28,11317.32,14.20,343.40,Lunch/Dinner,Lunch
633,Fish Biryani,"Chicken Curry, Ginger Chicken, Chickpea Salad,...","Fish Biryani with Chicken Curry, Ginger Chicke...","Rice, Fish, , onion, Spices, curry leaves, ...","400.0, 200.0, 80.0, 20.0, 32.0, 10.8, 360.0, 4...","SLA008, SLF006, , SLD060, SLI006, SLK004, SLK0...",7340.0,226.60,467.72,541.08,...,1685.44,625.40,10836.0,9247.40,6314.08,10564.28,48.00,352.28,Lunch/Dinner,Lunch
634,Fish Biryani,"Devilled Fish, Chickpea Salad, Devilled Beef, ...","Fish Biryani with Devilled Fish, Chickpea Sala...","Rice, Fish, , onion, Spices, curry leaves, ...","400.0, 200.0, 80.0, 20.0, 12.0, 10.8, 200.0, 4...","SLA008, SLF006, , SLD060, SLI006, SLK004, SLK0...",11580.0,319.80,897.52,541.08,...,1799.60,836.16,12304.0,21847.72,19424.60,12553.36,48.00,352.28,Lunch/Dinner,Lunch
635,Fish Biryani,"Chicken Curry, Devilled Chicken, Ginger Chicke...","Fish Biryani with Chicken Curry, Devilled Chic...","Rice, Fish, , onion, Spices, curry leaves, ...","400.0, 200.0, 80.0, 20.0, 32.0, 10.8, 410.0, 4...","SLA008, SLF006, , SLD060, SLI006, SLK004, SLK0...",10736.0,274.48,885.60,401.88,...,1706.76,547.92,10272.0,21376.68,19275.28,11317.32,14.20,343.40,Lunch/Dinner,Lunch
636,Fish Biryani,"Chicken Curry, Devilled Fish, Ginger Chicken, ...","Fish Biryani with Chicken Curry, Devilled Fish...","Rice, Fish, , onion, Spices, curry leaves, ...","400.0, 200.0, 80.0, 20.0, 32.0, 10.8, 260.0, 4...","SLA008, SLF006, , SLD060, SLI006, SLK004, SLK0...",10736.0,274.48,885.60,401.88,...,1706.76,547.92,10272.0,21376.68,19275.28,11317.32,14.20,343.40,Lunch/Dinner,Lunch

In [6]:
# using Meal time colummn seperate the data into breakfast, lunch and dinner
breakfast_df = df[df['Meal_time'] == 'Breakfast']
lunch_df = df[df['Meal_time'] == 'Lunch']
dinner_df = df[df['Meal_time'] == 'Dinner']

In [7]:
lunch_df.head()

,Main Meal,Side Meal,Complete Meal,Ingredients,Quantities,Meal_Ingredient_Ids,Energy(Kcal),Protein(g),Total fat(g),Carbohydrates(g),...,Magnesium(mg),Sodium(mg),Potassium(mg),Saturated Fatty Acids(mg),Monounsaturated Fatty Acids(mg),Polyunsaturated Fatty Acids(mg),Free sugar(g),Starch(g),Meal Time,Meal_time
13,Lamprais,Chicken Curry,Lamprais with Chicken Curry,"Rice, Meat, Spices, Chicken, Coconut milk","100.0, 30.0, 15.0, 40.0, 10.0","SLA008, SLH009, SLK004, SLH006, SLI006",1444.0,31.61,111.08,79.41,...,42.36,32.51,457.0,1495.08,1384.63,900.27,0.14,76.06,Lunch/Dinner,Lunch
14,Lamprais,Chicken Curry,Lamprais with Chicken Curry,"Rice, Meat, Spices, Chicken, Coconut milk","100.0, 30.0, 15.0, 40.0, 10.0","SLA008, SLH009, SLK004, SLH006, SLI006",1444.0,31.61,111.08,79.41,...,42.36,32.51,457.0,1495.08,1384.63,900.27,0.14,76.06,Lunch/Dinner,Lunch
30,Vegetable Fried Rice,Chicken Curry,Vegetable Fried Rice with Chicken Curry,"Rice, Vegetables, onion, Spices, curry leave...","100.0, 20.0, 20.0, 15.0, 3.0, 2.5, 40.0","SLA008, SLB002, SLD007, SLD060, SLI006, SLK004...",1559.0,41.66,112.83,90.83,...,313.01,121.40,1671.0,1924.84,1455.30,1791.06,4.47,81.32,Lunch/Dinner,Lunch
31,Vegetable Fried Rice,Parippu,Vegetable Fried Rice with Parippu,"Rice, Vegetables, onion, Spices, curry leave...","100.0, 20.0, 20.0, 15.0, 3.0, 2.5, 10.0, 5.0","SLA008, SLB002, SLD007, SLD060, SLI006, SLK004...",1991.0,46.10,113.95,188.36,...,638.83,137.78,4733.0,3330.84,1730.30,5855.06,6.38,164.36,Lunch/Dinner,Lunch
32,Vegetable Fried Rice,Wambatu Moju,Vegetable Fried Rice with Wambatu Moju,"Rice, Vegetables, onion, Spices, curry leave...","100.0, 20.0, 25.0, 5.5, 3.0, 2.5, 20.0, 10.0","SLA008, SLB002, SLD007, SLD060, SLI006, SLK004...",1383.0,18.52,103.59,90.83,...,292.83,90.98,1369.0,1146.84,471.30,1436.06,4.47,81.32,Lunch/Dinner,Lunch

In [8]:
# Function to generate a single random meal combination
def generate_random_combination():
    breakfast = breakfast_df.sample(n=1).iloc[0]
    lunch = lunch_df.sample(n=1).iloc[0]
    dinner = dinner_df.sample(n=1).iloc[0]

    # Combine ingredients (unique values only)
    combined_ingredients = set(breakfast['Ingredients'].split(', ') +
                               lunch['Ingredients'].split(', ') +
                               dinner['Ingredients'].split(', '))

    # Calculate the total nutritional values
    total_nutrition = {
        'Total Energy (Kcal)': breakfast['Energy(Kcal)'] + lunch['Energy(Kcal)'] + dinner['Energy(Kcal)'],
        'Total Protein (g)': breakfast['Protein(g)'] + lunch['Protein(g)'] + dinner['Protein(g)'],
        'Total Fat (g)': breakfast['Total fat(g)'] + lunch['Total fat(g)'] + dinner['Total fat(g)'],
        'Total Carbohydrates (g)': breakfast['Carbohydrates(g)'] + lunch['Carbohydrates(g)'] + dinner['Carbohydrates(g)'],
        'Total Magnesium (mg)': breakfast['Magnesium(mg)'] + lunch['Magnesium(mg)'] + dinner['Magnesium(mg)'],
        'Total Sodium (mg)': breakfast['Sodium(mg)'] + lunch['Sodium(mg)'] + dinner['Sodium(mg)'],
        'Total Potassium (mg)': breakfast['Potassium(mg)'] + lunch['Potassium(mg)'] + dinner['Potassium(mg)'],
        'Total Saturated Fatty Acids (mg)': breakfast['Saturated Fatty Acids(mg)'] + lunch['Saturated Fatty Acids(mg)'] + dinner['Saturated Fatty Acids(mg)'],
        'Total Monounsaturated Fatty Acids (mg)': breakfast['Monounsaturated Fatty Acids(mg)'] + lunch['Monounsaturated Fatty Acids(mg)'] + dinner['Monounsaturated Fatty Acids(mg)'],
        'Total Polyunsaturated Fatty Acids (mg)': breakfast['Polyunsaturated Fatty Acids(mg)'] + lunch['Polyunsaturated Fatty Acids(mg)'] + dinner['Polyunsaturated Fatty Acids(mg)'],
        'Total Free Sugar (g)': breakfast['Free sugar(g)'] + lunch['Free sugar(g)'] + dinner['Free sugar(g)'],
        'Total Starch (g)': breakfast['Starch(g)'] + lunch['Starch(g)'] + dinner['Starch(g)']
    }

    return {
        'Breakfast': breakfast['Complete Meal'],
        'Lunch': lunch['Complete Meal'],
        'Dinner': dinner['Complete Meal'],
        'Combined Ingredients': ', '.join(combined_ingredients),
        **total_nutrition
    }

# Generate 1000 combinations
combinations = [generate_random_combination() for _ in range(1000)]

# Convert to DataFrame
combinations_df = pd.DataFrame(combinations)

combinations_df.head()

,Breakfast,Lunch,Dinner,Combined Ingredients,Total Energy (Kcal),Total Protein (g),Total Fat (g),Total Carbohydrates (g),Total Magnesium (mg),Total Sodium (mg),Total Potassium (mg),Total Saturated Fatty Acids (mg),Total Monounsaturated Fatty Acids (mg),Total Polyunsaturated Fatty Acids (mg),Total Free Sugar (g),Total Starch (g)
0,Roast Bread with Bathala Curry,"Red Rice with Bean Curry, Vegetable Cutlets, K...","Red Rice with Dhal Curry, Breadfruit Chips, Si...","Coconut milk, flour, Flour, sugar, Red rice...",7423.3,180.044,580.150,471.779,1082.489,13117.590,8468.1,64516.450,15445.264,13613.890,21.528,418.226
1,"Red Rice with Beetroot Curry, Banana Blossom C...","Red Rice with Bathala Curry, Okra Curry, Sinha...","Red Rice with Chicken Curry, Mustard Greens Cu...","coconut milk, Jackfruit, Coconut milk, Red r...",12804.4,312.652,1217.700,651.968,2195.448,3916.428,14934.4,250430.276,27134.196,17497.056,76.460,494.080
2,"Red Rice with Brinjal Moju, Prawn Curry, Dry F...",Vegetable Fried Rice with Ala Badun,"Red Rice with Cabbage Mallung, Sesame Seed Sam...","Prawn, Sesame seed, Coconut milk, Rice, onion...",8366.8,273.422,611.792,596.336,1008.574,2846.964,8042.8,77947.184,10811.976,9149.578,32.378,475.804
3,"Red Rice with Gotu Kola Sambol, Snake Gourd Cu...","Red Rice with Gotu Kola Sambol, Snake Gourd Cu...","Red Rice with Cuttlefish Curry, Gotu Kola Samb...","Red rice, Coconut, curry leaves, Cuttlefish, ...",9086.0,175.728,710.056,737.172,2176.292,735.060,14462.4,131815.764,29473.112,16042.348,262.000,436.228
4,"Red Rice with Carrot Sambol, Dhal Vade, Mango ...","Red Rice with Cashew Curry, Egg Curry, Coconut...","Red Rice with Devilled Fish, Cashew Curry, Cau...","Coconut, Jackfruit, Coconut milk, Chili, oi...",11824.8,196.036,884.196,900.852,1812.780,535.532,10054.4,104270.572,107629.132,34412.932,363.436,489.452

In [9]:
combinations_df.shape

(1000, 16)

In [10]:
# sort total calories in ascending order
combinations_df.sort_values(by='Total Energy (Kcal)', inplace=True)
combinations_df.head()

,Breakfast,Lunch,Dinner,Combined Ingredients,Total Energy (Kcal),Total Protein (g),Total Fat (g),Total Carbohydrates (g),Total Magnesium (mg),Total Sodium (mg),Total Potassium (mg),Total Saturated Fatty Acids (mg),Total Monounsaturated Fatty Acids (mg),Total Polyunsaturated Fatty Acids (mg),Total Free Sugar (g),Total Starch (g)
642,String Hoppers with Chicken Curry,"Red Rice with Gotu Kola Sambol, Brinjal Moju, ...",Seafood Kottu with Ginger Chicken,"leeks, Fish, Coconut milk, Gotu Kola, Praw...",1847.45,73.0240,45.308,282.1585,552.1515,287.0955,4659.88,3359.8800,2487.9125,4912.1975,16.298,236.4465
916,String Hoppers with Prawn Curry,"Red Rice with Seer Fish Curry, Collard Greens ...",Egg Fried Rice with Devilled Fish,"Prawn, Coconut milk, Rice, Chili, salt, Coll...",2451.65,102.4585,131.298,211.6780,482.9285,394.5865,2995.98,10571.1400,8645.2255,6704.3600,2.926,192.1295
943,String Hoppers with Kochchi Sambol,Egg Fried Rice with Cashew Curry,String Hoppers with Coconut Sambol,"Green chili, Coconut, Coconut, curry leaves, ...",2466.50,61.2175,194.670,161.1450,682.4000,222.4575,2811.21,34444.0925,35729.9850,11488.5075,8.995,140.2000
625,Coconut Roti with Fish Curry,"Red Rice with Bitter Gourd Salad, potatoe chee...",Roast Bread with Indian Fish Curry,"Coconut, Bitter gourd, Coconut milk, Garlic, ...",2775.60,88.9400,248.151,228.3640,613.6320,1723.2050,4178.40,88463.9740,8625.4050,4789.0390,24.211,174.6070
988,Coconut Roti with Thalapath Fish Curry,Vegetable Fried Rice with Chicken Curry,"Red Rice with Octopus Curry, Mustard Greens Cu...","Coconut, Coconut milk, Rice, onion, Vegetabl...",3026.40,113.1970,171.062,269.6100,754.6360,1101.1510,4460.00,16938.3860,3823.2850,5338.0050,14.772,230.2240